Many to many relation
DjibrilM/postgres-course pull request #4
Opened 2023-08-26 21:58 UTC by DjibrilM

## In the following pull request I 
- introduced many to many relations 
- added additional tables

2023-08-26 22:33 UTC, NahnahAJ commented
## Project Status: INVALIDATED :red_circle: 
Hi @DjibrilM , 

While you made a great effort in this project, I can't go ahead and review your code.
<img src="https://media2.giphy.com/media/TiUYdWptTqn8yOk1Dp/giphy.gif"/>

## Invalid Code Review Request

- This is because you have submitted a project, that doesn't have the screenshot of your queries added to the pull request summary kindly add them as stated in the project requirements  :wink: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-26 23:27 UTC, Lucas-Masaba requested changes
# Hello @DjibrilM  👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️ 
- [ ] Like the previous reviewer mentioned, please add the screenshots of your queries on the pull request description.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-28 07:49 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @DjibrilM 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Tables are properly created ✔
- Data is properly inserted ✔
- Correct use of Git Flow ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-28 07:49 UTC, AbelG101 commented on queries.sql
> +LIMIT 1;
- [ ] Since the question asks for information about the animal as well I'd suggest adding a join to the animal relation which you can then display the animal's name for example.

2023-08-28 07:49 UTC, AbelG101 commented on queries.sql
- [ ] It seems like you're missing the query for the question "List all vets and their specialties, including vets with no specialties." so please add it to fulfill the project requirements.
- [ ] You also seem to be missing the query for the question "Details for most recent visit: animal information, vet information, and date of visit."
- [ ] And the query for the question "What specialty should Maisy Smith consider getting? Look for the species she gets the most."

2023-08-28 07:49 UTC, AbelG101 commented on queries.sql
- [ ] As part of the project requirements It is specifically stated to add the screenshot with the results of your queries to your Pull Request description instead of storing it in a directory in your repo which is making the size of your repo unnecessarily large I'd suggest you only upload it to the PR description.

2023-08-28 15:08 UTC, merged